In [56]:
from sklearn.datasets import load_boston
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, Ridge, RidgeClassifier, Lasso
from sklearn.metrics import mean_squared_error, accuracy_score
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV


In [4]:
boston=load_boston()

In [6]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [8]:
boston.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [5]:
boston.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [9]:
df= pd.DataFrame(boston.data,columns=boston.feature_names)
df['target']=pd.Series(boston.target)
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  394.63   2.94    33.4  
4       18.7  396.90   5.33    36.2  
..       ...     ...    ...     ...  
501     21.0  391.99   9.67    22.4  
502     21.0  396.90   9.08    20.6  
503     21.0  396.90   5.64    23.9  
504     21.0  393.45   6.48    22.0  
505     21.0  396.90   7.88    11.9  

[506 rows x 14 columns]

In [10]:
df.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
target     0
dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  target   506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB


In [12]:
x = df.drop('target',axis=1)
y = df['target']

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25, random_state=1)

### Linear Regression

In [58]:
##testing data accuracy
lr_model=LinearRegression()
lr_model.fit(x_train,y_train)
y_pred = lr_model.predict(x_test)
lr_testing_mse = mean_squared_error(y_test,y_pred)

In [51]:
##Training data accuaracy
lr_model=LinearRegression()
lr_model.fit(x_train,y_train)
y_pred_train = lr_model.predict(x_train)
lr_training_mse= mean_squared_error(y_train,y_pred_train)
lr_training_mse

22.477983821877896

### Ridge Regression

In [39]:
## Training data Accuracy
ridge_model = Ridge(alpha=0.008)
ridge_model.fit(x_train,y_train)
y_pred_ridge_train=ridge_model.predict(x_train)
mean_squared_error(y_train,y_pred_ridge_train)

22.47804792597288

In [40]:
##Testing Data Accuracy
ridge_model = Ridge(alpha=0.008)
ridge_model.fit(x_train,y_train)
y_pred_ridge=ridge_model.predict(x_test)
mean_squared_error(y_test,y_pred_ridge)

21.884638993794386

### Lasso Regression

In [73]:
## Testing data Set
lasso_model = Lasso(alpha=0.02)
lasso_model.fit(x_train,y_train)
y_pred_lasso=lasso_model.predict(x_test)
lasso_testing_mse=mean_squared_error(y_test,y_pred_lasso)
lasso_testing_mse

21.583247693735572

In [53]:
## Training Data Set
lasso_model = Lasso(alpha=0.02)
lasso_model.fit(x_train,y_train)
y_pred_lasso_train=lasso_model.predict(x_train)
lasso_training_mse=mean_squared_error(y_train,y_pred_lasso_train)

In [ ]:
overfitting >> traing mse is less & testing mse is more

In [54]:
lr_training_mse, lr_testing_mse

(22.477983821877896, 21.897765396049202)

In [55]:
 lasso_training_mse, lasso_testing_mse

(22.623285606954873, 21.583247693735572)

## Hyper parameter Tuning

In [67]:
a1 = np.arange(0.001,1,0.001)
a1

array([0.001, 0.002, 0.003, 0.004, 0.005, 0.006, 0.007, 0.008, 0.009,
       0.01 , 0.011, 0.012, 0.013, 0.014, 0.015, 0.016, 0.017, 0.018,
       0.019, 0.02 , 0.021, 0.022, 0.023, 0.024, 0.025, 0.026, 0.027,
       0.028, 0.029, 0.03 , 0.031, 0.032, 0.033, 0.034, 0.035, 0.036,
       0.037, 0.038, 0.039, 0.04 , 0.041, 0.042, 0.043, 0.044, 0.045,
       0.046, 0.047, 0.048, 0.049, 0.05 , 0.051, 0.052, 0.053, 0.054,
       0.055, 0.056, 0.057, 0.058, 0.059, 0.06 , 0.061, 0.062, 0.063,
       0.064, 0.065, 0.066, 0.067, 0.068, 0.069, 0.07 , 0.071, 0.072,
       0.073, 0.074, 0.075, 0.076, 0.077, 0.078, 0.079, 0.08 , 0.081,
       0.082, 0.083, 0.084, 0.085, 0.086, 0.087, 0.088, 0.089, 0.09 ,
       0.091, 0.092, 0.093, 0.094, 0.095, 0.096, 0.097, 0.098, 0.099,
       0.1  , 0.101, 0.102, 0.103, 0.104, 0.105, 0.106, 0.107, 0.108,
       0.109, 0.11 , 0.111, 0.112, 0.113, 0.114, 0.115, 0.116, 0.117,
       0.118, 0.119, 0.12 , 0.121, 0.122, 0.123, 0.124, 0.125, 0.126,
       0.127, 0.128,

In [68]:
a2 = np.arange(1,100,1)
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [69]:
alpha_range = np.append(a1,a2)

In [80]:
lasso_model=Lasso()
parameters = {'alpha':alpha_range}
gscv_lasso_model = GridSearchCV(lasso_model,param_grid=parameters)
gscv_lasso_model.fit(x_train,y_train)
gscv_lasso_model.best_estimator_

Lasso(alpha=0.002)

In [71]:
ridge_model=Ridge()
parameters = {'alpha':alpha_range}
gscv_lasso_model = GridSearchCV(ridge_model,param_grid=parameters,cv=5)
gscv_lasso_model.fit(x_train,y_train)
gscv_lasso_model.best_estimator_

Ridge(alpha=0.083)

In [72]:
##Testing Data Accuracy of ridge model
ridge_model = Ridge(alpha=0.083)
ridge_model.fit(x_train,y_train)
y_pred_ridge=ridge_model.predict(x_test)
mean_squared_error(y_test,y_pred_ridge)

21.77532599359745

In [78]:
## Testing data Set
lasso_model = Lasso(alpha=0.02)
lasso_model.fit(x_train,y_train)
y_pred_lasso=lasso_model.predict(x_test)
lasso_testing_mse=mean_squared_error(y_test,y_pred_lasso)
lasso_testing_mse

21.583247693735572

In [83]:
## Testing data Set
lasso_model_1 = Lasso(alpha=0.002)
lasso_model_1.fit(x_train,y_train)
y_pred_lasso=lasso_model_1.predict(x_test)
lasso_testing_mse=mean_squared_error(y_test,y_pred_lasso)
lasso_testing_mse

21.853383900967415

In [87]:
lasso_model=Lasso()
parameters = {'alpha':alpha_range}
Rscv_lasso_model = RandomizedSearchCV(lasso_model,param_distributions=parameters,cv=10)
Rscv_lasso_model.fit(x_train,y_train)
Rscv_lasso_model.best_estimator_

Lasso(alpha=0.009000000000000001)

In [88]:
## Testing data Set
lasso_model_1 = Lasso(alpha=0.009000000000000001)
lasso_model_1.fit(x_train,y_train)
y_pred_lasso=lasso_model_1.predict(x_test)
lasso_testing_mse=mean_squared_error(y_test,y_pred_lasso)
lasso_testing_mse

21.720675743201937