In [48]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
list1 = [2,3,4,5]
type(list1)

list

In [4]:
array = np.array([2,5,7,9])
array

array([2, 5, 7, 9])

#### checking the dimension of an array

In [6]:
array.ndim

1

In [7]:
array = np.array(list1)
array

array([2, 3, 4, 5])

In [8]:
array = np.array((2,5,7,9))
array

array([2, 5, 7, 9])

In [10]:
l1= [2,3.5,5,6.,5.9]
arr=np.array(l1)
arr

array([2. , 3.5, 5. , 6. , 5.9])

In [21]:
l1= [2,3.5,5,6.,3+4j,5.9]
arr=np.array(l1)
print(arr)
type(arr[0])
arr,arr.dtype

[2. +0.j 3.5+0.j 5. +0.j 6. +0.j 3. +4.j 5.9+0.j]


(array([2. +0.j, 3.5+0.j, 5. +0.j, 6. +0.j, 3. +4.j, 5.9+0.j]),
 dtype('complex128'))

## assgning a data type to the entire array

In [23]:
array = np.array((2,5,7,9), dtype='int')
array

array([2, 5, 7, 9])

In [24]:
array = np.array([2,5,7,9], dtype='float')
array

array([2., 5., 7., 9.])

In [25]:
array = np.array([2,5,7,9], dtype='complex')
array

array([2.+0.j, 5.+0.j, 7.+0.j, 9.+0.j])

In [33]:
array = np.array([2,5.5,7+8j,'9'])
array

array(['2', '5.5', '(7+8j)', '9'], dtype='<U64')

In [32]:
array = np.array([2,5,7,9], dtype='str')
type(array[0])

numpy.str_

In [31]:
array = np.array([2,5,7,9], dtype='object')
array

array([2, 5, 7, 9], dtype=object)

## Dimensions of an array

In [35]:
array = np.array([2,5,7,9])
array,array.ndim

(array([2, 5, 7, 9]), 1)

In [40]:
array = np.array(2.3)
array,array.ndim

(array(2.3), 0)

In [44]:
array = np.array([2.3])
array,array.ndim

(array([2.3]), 1)

In [41]:
array = np.array([[2,5,7,9]])
array,array.ndim

(array([[2, 5, 7, 9]]), 2)

In [45]:
array = np.array([[2,5,7,9],[3,4,6,7],[9,8,0,2]])
array,array.ndim

(array([[2, 5, 7, 9],
        [3, 4, 6, 7],
        [9, 8, 0, 2]]),
 2)

In [50]:
array = np.array([[2,5,7,9],
                  [3,4,6],
                  [9,8,0,2]])
array,array.ndim

(array([list([2, 5, 7, 9]), list([3, 4, 6]), list([9, 8, 0, 2])],
       dtype=object),
 1)

In [55]:
array = np.array([[[2,5,7,9],
                  [3,4,6,0],
                  [9,8,0,2]],
                [[2,5,7,9],
                  [3,4,6,0],
                  [9,8,0,2]]])
array,array.ndim

(array([[[2, 5, 7, 9],
         [3, 4, 6, 0],
         [9, 8, 0, 2]],
 
        [[2, 5, 7, 9],
         [3, 4, 6, 0],
         [9, 8, 0, 2]]]),
 3)

##### converting current dimensions into higher dimensions of array

In [56]:
array = np.array([2,5,7,9],ndmin=5)
array,array.ndim

(array([[[[[2, 5, 7, 9]]]]]), 5)

In [57]:
array = np.array([[2,5,7,9]],ndmin=1)
array,array.ndim

(array([[2, 5, 7, 9]]), 2)

In [58]:
array = np.array([[2,5],[7,9]],ndmin=1)
array,array.ndim

(array([[2, 5],
        [7, 9]]),
 2)

In [52]:
array = np.array([[[2,5,7,9],[3,4,6,7],[9,8,0,2]]])
array,array.ndim

(array([[[2, 5, 7, 9],
         [3, 4, 6, 7],
         [9, 8, 0, 2]]]),
 3)

In [54]:
list_dummy=[[[2,5,7,9],[3,4,6,7],[9,8,0,2]]]
np.array(list_dummy)
print(np.array(list_dummy).ndim)

3


## Indexing

In [60]:
array = np.array([2,5,7,9])
array[0],array[-1]

(2, 9)

In [63]:
array = np.array([[2,5,7,9],
                  [3,4,6,7],
                  [9,8,0,2]])
array[0]

array([2, 5, 7, 9])

In [64]:
array = np.array(         [   [2,5,7,9],[3,4,6,7],[9,8,0,2]    ]                    )
array[0]

array([2, 5, 7, 9])

In [65]:
array = np.array([[2,5,7,9],
                  [3,4,6,7],
                  [9,8,0,2]])
array[0][2]

7

In [67]:
array = np.array([[[2,5,7,9],
                   [3,4,6,7],
                   [9,8,0,2]],
                  [[9,0,0,9],
                   [7,0,0,7],
                   [2,0,0,2]]])
array[0]

array([[2, 5, 7, 9],
       [3, 4, 6, 7],
       [9, 8, 0, 2]])

In [68]:
array[1]

array([[9, 0, 0, 9],
       [7, 0, 0, 7],
       [2, 0, 0, 2]])

In [69]:
array[-1]

array([[9, 0, 0, 9],
       [7, 0, 0, 7],
       [2, 0, 0, 2]])

In [70]:
array[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [71]:
array[-1][1][-1]

7

In [72]:
array[0][2][0]

9

In [73]:
l1=[2,5,7,9]
l2=[9,8,0,2]
l1+l2

[2, 5, 7, 9, 9, 8, 0, 2]

In [74]:
arr1=np.array(l1)
arr2=np.array(l2)
arr1+arr2

array([11, 13,  7, 11])