## Slicing

In [1]:
import numpy as np


In [2]:
arr = np.array([2,5,4,7,8,3])
arr[:]

array([2, 5, 4, 7, 8, 3])

In [3]:
arr = np.array([2,5,4,7,8,3])
arr[::-1]

array([3, 8, 7, 4, 5, 2])

In [4]:
arr = np.array([2,5,4,7,8,3])
arr[::2]

array([2, 4, 8])

In [8]:
arr = np.array([2,5,4,7,8,3])
arr[2:6]

array([4, 7, 8, 3])

In [10]:
arr = np.array([2,5,4,7,8,3])
arr[2:-2:3]

array([4])

In [12]:
arr = np.array([[2,5,4],[7,8,3]])
arr[0][1]

5

In [14]:
arr = np.array([[2,5,4],[7,8,3]])
arr[:,:]                  #all rows & all columns

array([[2, 5, 4],
       [7, 8, 3]])

In [17]:
arr = np.array([[2,5,4],[7,8,3]])
arr[0:2,1:]        #all rows & 1 & 2 column

array([[5, 4],
       [8, 3]])

In [18]:
arr = np.array([[2,5,4],
                [7,8,3]])
arr[1:,:2]

array([[7, 8]])

In [25]:
arr = np.array([      [      [2,5,4],
                             [7,8,3]       ],
                      [      [4,4,6],
                             [7,8,9]       ]       ])
arr[0][:2,:2]
arr[1][:,1:]

array([[4, 6],
       [8, 9]])

In [36]:
arr = np.array([      [      [2,5,4],
                             [7,8,3]       ],
                      [      [4,4,6],
                             [7,8,9]       ]       ])
arr[0,:2,:2]


array([[[7, 8, 3]]])

In [40]:
arr = np.array([
                [     [      [2,5,4],
                             [7,8,3]       ],
                      [      [4,4,6],
                             [7,8,9]       ]       ],
                [     [      [0,0,0],
                             [1,1,1]       ],
                      [      [4,4,4],
                             [3,3,3]       ]       ]
                                                    ])
arr[:,:,:1,1:]
                                                
arr[1:,1:,:,2:]

array([[[[4],
         [3]]]])

## Reshape

In [41]:
array=np.array([2,3,4,5,6,7,8,9,1,0,12,15],ndmin=4)
array

array([[[[ 2,  3,  4,  5,  6,  7,  8,  9,  1,  0, 12, 15]]]])

In [46]:
array=np.array([2,3,4,5,6,7,8,9,1,0,12,15])
array=array.reshape(1,12)
# array.ndim
array

array([[ 2,  3,  4,  5,  6,  7,  8,  9,  1,  0, 12, 15]])

In [51]:
array=np.array([2,3,4,5,6,7,8,9,1,0,12,15])
array.reshape(2,6)
array.reshape(3,4)
array.reshape(4,3)
array.reshape(6,2)
array.reshape(12,1)

array([[ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [ 1],
       [ 0],
       [12],
       [15]])

In [62]:
array=np.array([2,3,4,5,6,7,8,9,1,0,12,15])
array=array.reshape(2,2,3)
display(array)
# array.reshape(3,2,2)
# array.reshape(2,3,2)
array.reshape(12)

array([[[ 2,  3,  4],
        [ 5,  6,  7]],

       [[ 8,  9,  1],
        [ 0, 12, 15]]])

array([ 2,  3,  4,  5,  6,  7,  8,  9,  1,  0, 12, 15])

In [64]:
list1=array.tolist()
list1

[[[2, 3, 4], [5, 6, 7]], [[8, 9, 1], [0, 12, 15]]]

In [65]:
array=np.array([2,3,4,5,6,7,8,9,1,0,12,15])
list1=array.tolist()
list1

[2, 3, 4, 5, 6, 7, 8, 9, 1, 0, 12, 15]

In [66]:
array=np.array([2,3,4,5,6,7,8,9,1,0,12,15])
list1=list(array)
list1

[2, 3, 4, 5, 6, 7, 8, 9, 1, 0, 12, 15]