### creating an empty array

In [5]:
import numpy as np
arr=np.array([])
arr

array([], dtype=float64)

### Creating an array of zeros using np.zeros()

In [7]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [8]:
arr=np.zeros(5,dtype='int')
arr

array([0, 0, 0, 0, 0])

In [11]:
arr=np.zeros((6,6),dtype='int')
arr

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

### Creating an array of ones using np.ones()

In [12]:
arr=np.ones((6,6),dtype='int')
arr

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [16]:
import pandas
pandas.DataFrame(arr,columns=[char for char in ('abacus')])

a  b  a  c  u  s
0  1  1  1  1  1  1
1  1  1  1  1  1  1
2  1  1  1  1  1  1
3  1  1  1  1  1  1
4  1  1  1  1  1  1
5  1  1  1  1  1  1

### crating a sequence of numbers using np.arange()

In [21]:
arr=np.arange(1,21,dtype='float')
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [22]:
arr=np.arange(1,21,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [26]:
arr=np.arange(21,3,-2).reshape(3,3)
arr

array([[21, 19, 17],
       [15, 13, 11],
       [ 9,  7,  5]])

### linspace() for creating sequence of numbers

In [58]:
dummy_arr=np.linspace(0,20,num=21)
dummy_arr
# 20/11

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20.])

In [59]:
import pandas as pd

In [74]:
np.linspace(0,30,6)

array([ 0.,  6., 12., 18., 24., 30.])

In [83]:
dict1={'amount': np.zeros(6,dtype='int'),
      'intrest': np.linspace(3,5.5,6),
     'Months':np.linspace(0,30,6)}

df=pd.DataFrame(dict1)
# df.set_index('index',inplace=True)


In [85]:
df['principle_intrest']=df['Months']*df['intrest']
df

amount  intrest  Months  principle_intrest
0       0      3.0     0.0                0.0
1       0      3.5     6.0               21.0
2       0      4.0    12.0               48.0
3       0      4.5    18.0               81.0
4       0      5.0    24.0              120.0
5       0      5.5    30.0              165.0