## np.eye()

In [6]:
import numpy as np
np.eye(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [7]:
np.eye(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [8]:
np.eye(3,5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [9]:
np.eye(3,5,dtype='int',k=2)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [12]:
np.eye(5,5,dtype='int',k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

## Identity()

In [15]:
np.identity(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [17]:
np.identity(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [21]:
np.identity(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## Random()

### random.rand()

In [23]:
np.random.rand(5)

array([0.32337403, 0.93783694, 0.14189212, 0.49856291, 0.08520748])

In [24]:
np.random.rand(10)

array([0.89632828, 0.54882893, 0.55401565, 0.71644131, 0.24603099,
       0.71345663, 0.95231698, 0.07134644, 0.06076943, 0.93713611])

In [27]:
np.random.rand(2,10)

array([[0.9332433 , 0.20715914, 0.96150347, 0.77993127, 0.57778991,
        0.1025818 , 0.04598282, 0.59316377, 0.15814054, 0.36626243],
       [0.79534533, 0.9494988 , 0.76040426, 0.40244569, 0.9517711 ,
        0.01553668, 0.15880139, 0.78497533, 0.86987945, 0.94106605]])

### random.random()

In [36]:
np.random.random(4)

array([0.73615837, 0.47212059, 0.89838232, 0.90098838])

### random.ranf()

In [51]:
np.random.ranf(5)

array([0.88763929, 0.67216105, 0.51544782, 0.65194862, 0.60454319])

In [50]:
np.random.ranf(10).reshape(5,2)

array([[0.92815095, 0.47393611],
       [0.64837018, 0.34050605],
       [0.22783767, 0.99159592],
       [0.38410137, 0.24212327],
       [0.24026757, 0.47610692]])

### <B> <font color= 'red'>np.random.randint()

In [29]:
np.random.randint(1,20,size=10,dtype='int')

array([ 7, 18,  6,  5, 11,  1, 15, 16, 16,  6])

In [32]:
np.random.randint(1,high=None,size=None,dtype='int')

0

In [33]:
np.random.randint(10,high=99,size=2,dtype='int')

array([91, 52])

### random.randn()

In [37]:
np.random.randn(5)

array([-1.59581493,  1.2550214 , -0.27534958,  0.40309568, -0.38046981])

In [44]:
np.random.randn(12).reshape(3,4)

array([[-0.42383725, -0.45726839,  0.27409758,  0.54809305],
       [-0.4157035 ,  1.38352357, -1.20038873,  0.38429999],
       [ 0.09468825,  0.42065671, -0.85568345, -1.52547281]])

In [46]:
np.random.randn(2,2)

array([[-0.73439805, -0.78271904],
       [-0.61558512, -0.98014698]])

## Sort()

In [ ]:
np.sort()     -- sorts the array

In [55]:
ran_nums=np.random.randint(1,99,25)
ran_nums

array([88, 29, 60, 78, 46, 91, 27, 62, 76, 20,  6, 10, 82, 38, 13, 20, 32,
       62, 38, 37, 50, 77, 94,  1, 15])

In [56]:
np.sort(ran_nums)

array([ 1,  6, 10, 13, 15, 20, 20, 27, 29, 32, 37, 38, 38, 46, 50, 60, 62,
       62, 76, 77, 78, 82, 88, 91, 94])

In [60]:
np.sort(ran_nums)[::-1]

array([94, 91, 88, 82, 78, 77, 76, 62, 62, 60, 50, 46, 38, 38, 37, 32, 29,
       27, 20, 20, 15, 13, 10,  6,  1])

In [136]:
array1=np.array([2,3,4,10])
array1[2]=10
array1


array([ 2,  3, 10, 10])

## Insert()

In [137]:
array1=np.array([2,3,4,10])
np.insert(array1,3,100)

array([  2,   3,   4, 100,  10])

In [138]:
array1=np.array([2,3,4,10])
array2=np.array([5,5,5])
np.insert(array1,3,array2)

array([ 2,  3,  4,  5,  5,  5, 10])

## Append()

In [103]:
array1=np.array([2,3,4])
array1=np.append(array1,(10,20))
array1

array([ 2,  3,  4, 10, 20])

In [105]:
array1=np.array([2,3,4,10])
array2=np.array([5,6,7,8])
array3=np.array([5,6,9,8])
display(array1,array2)
np.append(array1,array2)

array([ 2,  3,  4, 10])

array([5, 6, 7, 8])

array([ 2,  3,  4, 10,  5,  6,  7,  8])

In [75]:
# array1+array2

In [79]:
array1=np.array([2,3,4,10])
array2=np.array([[5,6],[7,8]])
display(array1,array2)
np.append(array1,array2)

array([ 2,  3,  4, 10])

array([[5, 6],
       [7, 8]])

array([ 2,  3,  4, 10,  5,  6,  7,  8])

In [80]:
np.append(array2,array1)

array([ 5,  6,  7,  8,  2,  3,  4, 10])

In [87]:
array1=np.array([[2,3]])

array2=np.array([[5,6],
                 [7,8]])

display(array1,array2)
np.append(array1,array2,axis=0)

array([[2, 3]])

array([[5, 6],
       [7, 8]])

array([[2, 3],
       [5, 6],
       [7, 8]])

In [91]:
array1=np.array([[2,3],
                 [4,5]])

array2=np.array([[5,6]])

display(array1,array2)
np.append(array1,array2,axis=0)

array([[2, 3],
       [4, 5]])

array([[5, 6]])

array([[2, 3],
       [4, 5],
       [5, 6]])

In [90]:
array1=np.array([[2,3],
                 [4,5]])

array2=np.array([[5],
                 [7]])

np.append(array1,array2,axis=1)

array([[2, 3, 5],
       [4, 5, 7]])

## Concatenate()

In [99]:
array1=np.array([2,3,4])
array1=np.concatenate([array1,[10,]])
array1

array([ 2,  3,  4, 10])

In [95]:
array1=np.array([2,3,4])
array2=np.array([5,6,7,8])
array1=np.concatenate((array1,array2))
array1

array([2, 3, 4, 5, 6, 7, 8])

In [101]:
array1=np.array([2,3,4])
array2=np.array([5,6,7,8])
array3=np.array([9,10])
array3=np.concatenate([array1,array2,array3])
array3

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
array1=np.array([[2,3],
                 [4,5]])

array2=np.array([[5,6]])

display(array1,array2)
np.concatenate([array1,array2],axis=0)

array([[2, 3],
       [4, 5]])

array([[5, 6]])

array([[2, 3],
       [4, 5],
       [5, 6]])

In [108]:
array1=np.array([[2,3],
                 [4,5]])

array2=np.array([[5],
                 [7]])

np.concatenate((array1,array2),axis=1)

array([[2, 3, 5],
       [4, 5, 7]])

## For Loop

In [120]:
array1=np.array([2,3,4,10])

In [121]:
for i in array1:
    print(i)

2
3
4
10


In [122]:
for i,value in enumerate(array1):
    print(i,value)

0 2
1 3
2 4
3 10


In [123]:
for i,value in np.ndenumerate(array1):
    print(i,value)

(0,) 2
(1,) 3
(2,) 4
(3,) 10


In [124]:
array1=np.array([[2,3],
                 [4,5]])

for i in array1:
    print(i)

[2 3]
[4 5]


In [117]:
for i in array1:
    for j in i:
        print(j,end=' ')

2 3 4 5 

## nditer()

In [118]:
for i in np.nditer(array1):
    print(i)

2
3
4
5


In [125]:
for i,value in enumerate(array1):
    print(i,value)

0 [2 3]
1 [4 5]


In [126]:
for i,value in np.ndenumerate(array1):
    print(i,value)

(0, 0) 2
(0, 1) 3
(1, 0) 4
(1, 1) 5


In [145]:
list1=[3,4,5]
x=np.array(list1,dtype='str')
1+int(x[0])

4

<B><font color= 'red'>NOTE: the object data type basically mentions that the type of every individual element in the array is preserved to its original dtype.Which means for int, it'll be int & for striung it will be string

In [166]:
list1=[3,4.7,5,'h']
x=np.array(list1,dtype='object')
x[1]+1


5.7

In [150]:
list1=[3,4.7,5,'h']
x=np.array(list1,dtype='object')
x[1]+1


TypeError: can only concatenate str (not "int") to str