## Ceil

In [3]:
import numpy as np
np.ceil(2.2)

3.0

In [9]:
round(2.6)

3

In [10]:
round(-2.6)      -2.5

-3

In [11]:
np.ceil(-2.8)

-2.0

In [12]:
np.ceil([2.1,3.5,4.8,9.21])

array([ 3.,  4.,  5., 10.])

## floor

In [ ]:
floor reduces the number to its closest minimum whole number

In [13]:
np.floor([2.2])

array([2.])

In [16]:
np.floor([2.99999999])

array([2.])

In [15]:
np.floor([-2.8])

array([-3.])

In [17]:
np.floor([2.1,3.5,4.8,9.21])

array([2., 3., 4., 9.])

## around()

In [ ]:
around works exactly the same way as round function

In [37]:
np.around(2.5)

2.0

In [39]:
np.around(2.5000001)

3.0

In [21]:
np.around(2.6)

3.0

In [22]:
np.around(-2.6)

-3.0

In [23]:
np.around(-2.2)

-2.0

In [26]:
round(2.467,2)

2.47

In [28]:
np.around(2.467,2)

2.47

In [29]:
np.around([[2.467,2.7],
           [7.78,5.5]])

array([[2., 3.],
       [8., 6.]])

In [34]:
np.around([[2.467,2.77],
           [7.46833,5.589]],2)

array([[2.47, 2.77],
       [7.47, 5.59]])

## copy

In [40]:
array1=np.array([4,5,6,2])
array1

array([4, 5, 6, 2])

In [41]:
array2=array1.copy()
array2

array([4, 5, 6, 2])

In [46]:
array1=np.array([[4,5],[6,2]])
array1

array([[4, 5],
       [6, 2]])

In [47]:
array2=array1.copy()     #works as deepcopy 
array2

array([[4, 5],
       [6, 2]])

In [48]:
array1[1,1]=100
array1

array([[  4,   5],
       [  6, 100]])

In [49]:
array2

array([[4, 5],
       [6, 2]])

In [54]:
from copy import deepcopy
array1=np.array([[4,5],[6,2]])
array2=deepcopy(array1)     #works as deepcopy 
array1,array2

(array([[4, 5],
        [6, 2]]),
 array([[4, 5],
        [6, 2]]))

In [55]:
array1[1,1]=200
array2

array([[4, 5],
       [6, 2]])

In [56]:
from copy import deepcopy,copy
array1=np.array([[4,5],[6,2]])
array2=array1.copy()    #works as deepcopy 
array1,array2

(array([[4, 5],
        [6, 2]]),
 array([[4, 5],
        [6, 2]]))

In [57]:
array1[1,1]=200
array2

array([[4, 5],
       [6, 2]])

## np.where

In [4]:
import numpy as np
arr=np.array([4,5,6,2,4])
np.where(arr==4)

(array([0, 4], dtype=int64),)

In [61]:
arr=np.array([4,5,6,2,4])
np.where(arr>=4)

(array([0, 1, 2, 4], dtype=int64),)

In [62]:
arr=np.array([4,5,6,2,4])
np.where(arr==1)

(array([], dtype=int64),)

In [64]:
l1=[4,5,6,2,4]
l1.index(4,2)

4

In [65]:
indexes=[index for index,value in enumerate(l1) if value==4]
indexes

[0, 4]

In [67]:
arr=np.array([4,5,6,2,4])
np.where(arr%2==0)

(array([0, 2, 3, 4], dtype=int64),)

In [68]:
arr=np.array([4,5,6,2,4])
np.where(arr==4,8,arr)

array([8, 5, 6, 2, 8])

In [71]:
arr=np.array([4,5,6,2,4])
np.where(arr==2*2,np.NaN,arr)

array([nan,  5.,  6.,  2., nan])

In [72]:
arr=np.array([4,5,6,2,4])
np.where(arr==2*2,None,arr)

array([None, 5, 6, 2, None], dtype=object)

In [79]:
# import pandas as pd
# df=pd.DataFrame(arr,columns={'random_no.s'})
# df

In [80]:
# df.to_excel('random numbers file.xlsx')

In [81]:
# dataframe=pd.read_excel('random numbers file.xlsx')
# dataframe

In [83]:
dir(arr)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [84]:
arr=np.array([4,5,6,2,4])
np.argmax(arr)

2

In [88]:
arr=np.array([4,2,5,6,2,4])
np.argmin(arr)

1

In [89]:
arr=np.array([4,2,5,6,4])
np.argsort(arr)

array([1, 0, 4, 2, 3], dtype=int64)

In [90]:
np.size(arr)

5

In [91]:
array1=np.array([[4,5],[6,2]])
np.size(array1)

4