In [20]:
import numpy as np
arr=np.array([5,4,2,5,6,7,4,12,56,34,89,100000])
np.sum(arr)

100224

In [14]:
# sum of all numbers devided by total numbers
np.mean(arr)

9110.818181818182

In [15]:
# middle numbers of sorted array
display(np.sort(arr))
np.median(arr)

array([     2,      4,      4,      5,      6,      7,     12,     34,
           56,     89, 100000])

7.0

In [21]:
from statistics import mode
#highest occuring number whichever comes first
mode(arr)

5

In [22]:
np.std(arr)

27632.9237203256

In [23]:
arr=np.array([5,4,2,5,6,7,4,12,56,34,89])
arr+2

array([ 7,  6,  4,  7,  8,  9,  6, 14, 58, 36, 91])

In [24]:
arr=np.array([5,4,2,5,6,7,4,12,56,34,89])
arr-2

array([ 3,  2,  0,  3,  4,  5,  2, 10, 54, 32, 87])

In [25]:
arr=np.array([5,4,2,5,6,7,4,12,56,34,89])
arr*2

array([ 10,   8,   4,  10,  12,  14,   8,  24, 112,  68, 178])

In [26]:
arr=np.array([5,4,2,5,6,7,4,12,56,34,89])
arr/2

array([ 2.5,  2. ,  1. ,  2.5,  3. ,  3.5,  2. ,  6. , 28. , 17. , 44.5])

In [27]:
arr=np.array([5,4,2,5,6,7,4,12,56,34,89])
arr//2

array([ 2,  2,  1,  2,  3,  3,  2,  6, 28, 17, 44], dtype=int32)

In [28]:
arr=np.array([5,4,2,5,6,7,4,12,56,34,89])
arr%2

array([1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1], dtype=int32)

In [31]:
np.square(arr)
np.power(arr,3)

array([   125,     64,      8,    125,    216,    343,     64,   1728,
       175616,  39304, 704969], dtype=int32)

In [33]:
arr**2

array([  25,   16,    4,   25,   36,   49,   16,  144, 3136, 1156, 7921],
      dtype=int32)

In [36]:
arr1=np.array([5,4,2,5,6,7,])
arr2=np.array([4,12,56,34,89,0])
arr1+arr2

array([ 9, 16, 58, 39, 95,  7])

In [37]:
arr1=np.array([5,4,2,5,6,7,])
arr2=np.array([4,12,56,34,89,0])
arr1-arr2

array([  1,  -8, -54, -29, -83,   7])

In [38]:
arr1=np.array([5,4,2,5,6,7,])
arr2=np.array([4,12,56,34,89,0])
arr1*arr2

array([ 20,  48, 112, 170, 534,   0])

In [39]:
arr1=np.array([[5,4,2],[5,6,7]])
arr2=np.array([[4,12,56],[34,89,0]])
arr1+arr2

array([[ 9, 16, 58],
       [39, 95,  7]])

In [40]:
np.add(arr1,arr2)

array([[ 9, 16, 58],
       [39, 95,  7]])

In [41]:
np.subtract(arr1,arr2)

array([[  1,  -8, -54],
       [-29, -83,   7]])

In [42]:
np.multiply(arr1,arr2)

array([[ 20,  48, 112],
       [170, 534,   0]])

In [43]:
np.divide(arr1,arr2)

<ipython-input-43-07a616d6a01b>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(arr1,arr2)


array([[1.25      , 0.33333333, 0.03571429],
       [0.14705882, 0.06741573,        inf]])