In [6]:
import numpy as np



# SN 	Function	Definition
1       	dot()	             It is used to calculate the dot product of two arrays.

2	        vdot()             	It is used to calculate the dot product of two vectors.

3  	       inner() 	            It is used to calculate the inner product of two arrays.

4	      matmul()             	It is used to calculate the matrix multiplication of two arrays.

5	        det()	            It is used to calculate the determinant of a matrix.

6          solve()	            It is used to solve the linear matrix equation.

7	         inv()               It is used to calculate the multiplicative inverse of the matrix.

In [7]:
A = np.array([[3,4],[5,6]])
B = np.array([15,20])

In [8]:
np.linalg.inv(A)

array([[-3. ,  2. ],
       [ 2.5, -1.5]])

In [9]:
np.linalg.solve(A,B)

array([-5. ,  7.5])

In [10]:
A = np.array([[3,4,8],[5,6,-2],[4,-2,6]])
B = np.array([15,20,24])
np.linalg.solve(A,B)

array([ 5.07317073, -0.77439024,  0.3597561 ])