In [2]:
import numpy as np
arr1=np.array([[3,4],[5,5]])
arr2=np.array([[4,6],[9,0]])


In [4]:
arr1*arr2

array([[12, 24],
       [45,  0]])

## Matrix dot product

In [ ]:
for matrix dot product: number of columns of first matrix has to be equivalent to the number of rows of second matrix

In [8]:
matrix1=np.array([[3,4],
                  [5,5]])
matrix2=np.array([[4,6],
                  [9,0]])


# 3*4+4*9   3*6+4*0
# 5*4+5*9   5*6+5*0

In [9]:
np.dot(matrix1,matrix2)

array([[48, 18],
       [65, 30]])

In [10]:
matrix1=np.array([[3,4],
                  [5,5],
                  [1,1]])
matrix2=np.array([[4,6],
                  [9,0]])

np.dot(matrix1,matrix2)

array([[48, 18],
       [65, 30],
       [13,  6]])

In [11]:
matrix1=np.array([[3,4],
                  [5,5],
                  [1,1]])
matrix2=np.array([[4,6,2],
                  [9,0,0]])

np.dot(matrix1,matrix2)

array([[48, 18,  6],
       [65, 30, 10],
       [13,  6,  2]])

In [12]:
np.dot(matrix2,matrix1)

array([[44, 48],
       [27, 36]])

In [14]:
matrix1=np.array([[3,4],
                  [5,5],
                  [1,1]])
matrix2=np.array([[3,4],
                  [5,5],
                  [1,1]])
np.dot(matrix2,matrix1)
# np.dot(matrix1,matrix2)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)