In [1]:
import numpy as np

# Log functions

In [16]:
np.log(np.exp(1))     #natural log is log e to the base whatever number

1.0

In [21]:
np.exp(1)

2.718281828459045

In [22]:
np.log(2.718281828459045)

1.0

In [17]:
np.log(0)

<ipython-input-17-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [2]:
np.log(1)

0.0

In [4]:
np.log(2)

0.6931471805599453

In [5]:
np.log(10)

2.302585092994046

In [8]:
np.log10(10)       # log 10 to the base whatever number

1.0

In [ ]:
10**1
10**2
10**3

In [10]:
np.log10(100)

2.0

In [11]:
np.log10(1000)

3.0

In [37]:
np.log10(1)

0.0

In [38]:
np.log(0.10)

-2.3025850929940455

In [41]:
np.log(0.000000000000000000000000000000000000)

<ipython-input-41-efc6eddd505b>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0.000000000000000000000000000000000000)


-inf

In [15]:
np.log2(2)

1.0

In [30]:
np.log2(1)

0.0

In [36]:
np.log2(0.9)

-0.15200309344504995

## Trignometry

In [ ]:
"SOHCAHTOA"!

SOH
Sine = Opposite / Hypotenuse

CAH
Cosine = Adjacent / Hypotenuse

TOA
Tangent = Opposite / Adjacent

Standard Angles in a Trigonometric Table
The values of trigonometric ratios for the angles 0°, 30°, 45°, 60°, and 90° in a trigonometry table are commonly used to solve the trigonometry problems. These values are associated with the measurement of the lengths and the angles of a right-angle triangle. Thus, 0°, 30°, 45°, 60°, and 90° are called the standard angles in trigonometry.

Trigonometry Table for Standard Angles
The trigonometric table is simply a collection of values of trigonometric functions of various standard angles including 0°, 30°, 45°, 60°, 90°, along with with other angles like 180°, 270°, and 360° included, in a tabular format. It is easy to predict the values of the trig ratios in a trigonometric table and to use the table as a reference to calculate trigonometric values for various other angles, due to the patterns existing within trigonometric ratios and even between angles.

The table consists of trigonometric ratios – sine, cosine, tangent, cosecant, secant, and cotangent. In short, these ratios are written as sin, cos, tan, cosec, sec, and cot. It is best to remember the values of the trigonometric ratios of these standard angles.

trigonometric table

In [44]:
np.sin()

-0.4097717985741408

In [46]:
np.pi

3.141592653589793

In [45]:
np.sin(np.pi/6)

0.49999999999999994

In [53]:
1/2

0.5

In [47]:
np.sin(np.pi/4)

0.7071067811865476

In [48]:
np.sin(np.pi/2)

1.0

In [50]:
np.cos(np.pi/2)

6.123233995736766e-17

In [51]:
np.tan(np.pi/2)

1.633123935319537e+16

In [52]:
22/7

3.142857142857143

## degree to radian

In [55]:
np.deg2rad(0)

0.0

In [56]:
np.deg2rad(30)

0.5235987755982988

In [57]:
np.sin(0.5235987755982988)

0.49999999999999994

In [58]:
np.pi/6

0.5235987755982988

In [59]:
np.deg2rad(45)

0.7853981633974483

In [60]:
np.cos(0.7853981633974483)

0.7071067811865476

In [61]:
1/(np.sqrt(2))

0.7071067811865475

In [65]:
np.deg2rad([0,30,45,60,90,120,150,180])

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633,
       2.0943951 , 2.61799388, 3.14159265])

In [71]:
np.radians(30),np.radians(45)

(0.5235987755982988, 0.7853981633974483)

## radian to degree

In [63]:
np.rad2deg(np.pi/6)

29.999999999999996

In [64]:
np.rad2deg(np.pi/4)

45.0

In [67]:
np.degrees(np.pi/6)

29.999999999999996

In [68]:
np.degrees(np.pi/4)

45.0

In [73]:
n, p = 10, .5  # number of trials, probability of each trial
s = np.random.binomial(n, p, 10)
s

array([5, 4, 3, 7, 6, 4, 5, 5, 3, 4])

In [74]:
sum(np.random.binomial(9, 0.1, 20000) == 0)/20000

0.3849

In [81]:
string=""
for i in range(0,8):
    v2=np.random.randint(0,9,size=8)
#     if i==0:
    string="".join(str(v2))
# else:
#     string=string+"".join(str(v2))
print(string)
type(string)
# string.split()
string[1:-1].replace(' ','')

[1 2 4 3 6 0 8 8]


'12436088'

In [ ]:
class A():
    method_B(cls,):
        return
    
# obj=A
A.method()